/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leapfrog.ui;

import com.leapfrog.coursedao.CourseDAO;
import com.leapfrog.coursedaoimpl.CourseDAOImpl;
import com.leapfrog.courses.Course;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Lenovo
 */
public class CourseUI extends javax.swing.JFrame {
private CourseDAO coursedao=new CourseDAOImpl();
    /**
     * Creates new form CourseUI
     */
    public CourseUI() {
        initComponents();
        try{
            String[] columns={"Id","Name","Description","Fees","Added Date","Modifed Date","Status"}; 
        tblcourse.setModel(new CourseTableModel(columns,coursedao.getAll()));
        }
        catch(ClassNotFoundException|SQLException ce){
            JOptionPane.showMessageDialog(null, ce.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcourse = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/leapfrog/resources/ad.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonClick(evt);
            }
        });

        tblcourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblcourse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonClick
          new CourseAdduI().setVisible(true);
    }//GEN-LAST:event_addButtonClick

    /**
     * @param args the command line arguments
     */
   private class CourseTableModel extends AbstractTableModel{
       private String columns[];
       private List<Course> courseList;

        public CourseTableModel(String[] columns, List<Course> courseList) {
            this.columns = columns;
            this.courseList = courseList;
        }
       
       

        @Override
        public int getRowCount() {
           return courseList.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {  
            Course course=courseList.get(rowIndex);
            switch(columnIndex){
                case 0:
                    return course.getId();
                case 1:
                    return course.getName();
                case 2:
                    return course.getFees();
                case 3:
                    return course.getAdded_date();
                case 4:
                    return course.isStatus();
               
                    
            }
            return null;
        }
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcourse;
    // End of variables declaration//GEN-END:variables
}
